### PR TITLE
Added posibility to set additinal headers to requests.

### PR DESCRIPTION
**Pull request by lauer**
This is added as a method on the QuickPay class, together
with added an extra parameter on initialize.

refs gh-56

### CODE REVIEW

**Comment by lauer** [comment]
What is status on this issue? Can it be merged?

**Comment by lauer** [comment]
@lsolesen can I get some feedback on my PR?

**Comment by AndreasHerss** [comment]
come on, this should be supported! as your api requires this for some things, like the callback-url.... @nielsek  @ta ?

**Comment by jesperholstjh** [comment]
Will this get merged or what is happening?

**Comment by ta** [comment]
It seems like the current maintainer is not available any more, sorry.

As we have no skilled in-house PHP resources, I'm afraid we'll to find a new maintainer.

If anyone is interested in maintaining this small library, please let me know.

**Comment by Sthing** [comment]
Hi @lauer 
I have accepted the position as maintainer.
Will look at the PR now.
/Søren Thing

**Comment by Sthing** [comment]
I have made a fed changes and resubmitted as https://github.com/QuickPay/quickpay-php-client/pull/60.
Thank you very much for your input.

**Pull request closed without merging**
