### PR TITLE
Clean up and bump minimum PHP version to 8.0

### PR DESCRIPTION
**Pull request by iMusicJJ**
- Cleans up the codebase
- Fixes tests
- Statically checks all code
- Bumps PHP version requirement to 8.0+
- Adds a 15s timeout to the curl handler, since when QP goes down, it doesn't timeout, it just hogs resources. This prevents the resource abuse.

### CODE REVIEW

**Comment by iMusicJJ** [comment]
If you want to merge the PR, I'll to adjust back the Composer package name. I'll do that as soon as I know whether or not you want these changes upstream :) 🎉

**Comment by RasmusGJ** [comment]
> If you want to merge the PR, I'll to adjust back the Composer package name. I'll do that as soon as I know whether or not you want these changes upstream :) 🎉

Hi there. I’ve been added as a collaborator, could you adjust the Composer package name? Thank you! :+1:

**Comment by iMusicJJ** [comment]
Will do.

Notably, this adds the ability to set timeout and get notified on timeouts. (We use this internally to failover to a backup gateway when Quickly has downtime)

Can be used like so:

```php
QuickPayAPI::$timeout = 30;
QuickPayAPI::$onTimeout ??= function () {
    event(new PaymentGatewayTimeout($this));

    throw new TimeoutException("No response from Quickpay within " . QuickPayAPI::$timeout . " seconds");
};
```

**Comment by iMusicJJ** [comment]
Name has been changed to align with `quickpay/quickpay-php-client`

It might make sense to release this as a new major version, as it does come with quite a bit of change.

**Review by RasmusGJ — APPROVED** [review]

**Review by CMeldgaard — APPROVED** [review]

**Comment by CMeldgaard** [comment]
@iMusicJJ that is the plan, to make PHP8 version 2.0

To be able to merge your PR into master, we need you to sign all you commits. This repo requires all commits to be signed.

**Comment by iMusicJJ** [comment]
It seems there's no good way to sign old commits. I am not sure what you're asking me to do in this case?

**Comment by CMeldgaard** [comment]
@iMusicJJ, this is properly the best way to do it:
https://superuser.com/questions/397149/can-you-gpg-sign-old-commits

**Comment by iMusicJJ** [comment]
Check to see if it's okay now. All commits I made are now verified, but anything by dependabot etc. is still unverified.

Cheers

**Comment by CMeldgaard** [comment]
@iMusicJJ We are almost there :D You need to add the public key to your github account. You do that in Settings > SSH and GPG keys

Her you kan add your key.

**Comment by iMusicJJ** [comment]
It's stange!

I do have my public key in my GH account. All commits that I made are verified; But commits from Dependabot aren't.

**Pull request merged**
