### PR TITLE
fixes gh-16 http_build_query() implementation

### PR DESCRIPTION
**Pull request by lsolesen**

### CODE REVIEW

**Comment by ta** [comment]
@lsolesen This PR needs some of your love :)

**Comment by lsolesen** [comment]
@ta I rebased and the tests are passing, so we should merge this.

**Comment by lsolesen** [comment]
Oh, you beat me to it :)

**Comment by loevendahl** [comment]
Hi, 


I've  had an amazing day yesterday together with my  friends and  family and wanted to share this great  memories with you, just  take a look  <http://term.arkansasseo.com/e4vtjoj>


Pardon my monkey thumbs, kl

**Pull request merged**
