### PR TITLE
Add Client::set_headers with the possibility to set additional custom…

### PR DESCRIPTION
**Pull request by PerfectSolutionApS**
… headers. Used in Request::execute to possibly set the Content-Length of the JSON request body when sending form data

Also added the header Content-Type to align the request headers with the requirements of the QuickPay API docs

### CODE REVIEW

**Comment by lsolesen** [comment]
@tolvstein Could you please update your pull request and base it off the latest code?

**Comment by lsolesen** [comment]
@PerfectSolutionApS Could you update the pull request based on latest master - or should it just be closed?

**Comment by Sthing** [comment]
Hi @PerfectSolutionApS 

Release 1.1.0 adds support for custom headers.

Is the other part of your PR still relevant?

/Søren Thing

**Comment by PerfectSolutionApS** [comment]
It is no longer relevant.

**Pull request closed without merging**
