### PR TITLE
Initial work on coveralls integration

### PR DESCRIPTION
**Pull request by lsolesen**
This is work in progress.

### CODE REVIEW

**Comment by ta** [comment]
@lsolesen Could you rebase this PR ?

**Comment by lsolesen** [comment]
@ta Rebased. Wait for results before merging.

**Comment by lsolesen** [comment]
@ta Did you have a chance to look this over?

**Comment by ta** [comment]
@lsolesen Sorry, have been away for easter. Could you rebase yet again?

**Comment by lsolesen** [comment]
@ta Ready to merge?

**Comment by ta** [comment]
@lsolesen Done - sorry for the delay

**Pull request merged**
