### PR TITLE
Update composer config with proper lib-curl requirement

### PR DESCRIPTION
**Pull request by acidtv**
PHP libs are required in the lib-<name> format, see https://getcomposer.org/doc/02-libraries.md#platform-packages

### CODE REVIEW

**Comment by lsolesen** [comment]
@acidtv Could you please update your pull request to the latest code?

**Comment by acidtv** [comment]
@lsolesen merged!

**Comment by lsolesen** [comment]
@acidtv You need to reroll this, as there is conflicts with the main branch. My guess is that you added a newline in the end of composer.json also in your PHP 5.3 pull request.

**Comment by lsolesen** [comment]
@acidtv You need to reroll this against the new master again. Please try to do it without merge commits.

You can `git rebase -i master` on your branch to avoid that.

**Comment by lsolesen** [comment]
Closing this. Added it myself before the 0.1.0 release.

**Pull request closed without merging**
